# Generated by Django 5.2.3 on 2025-06-13 15:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_users_first_name_remove_users_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='aze@in.com', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='MK', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Tom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='azerty1234', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+22991862280', max_length=128, region=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('conducteur', 'Conducteur'), ('passager', 'Passager')], default='passager', max_length=20),
            preserve_default=False,
        ),
    ]
