# Generated by Django 5.2.3 on 2025-06-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_remove_users_username_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=191, unique=True, verbose_name='email address'),
        ),
    ]
