# Generated by Django 5.2.3 on 2025-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileUser', '0003_rename_profil_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ville',
        ),
        migrations.AddField(
            model_name='profile',
            name='brand',
            field=models.CharField(blank=True, help_text='Marque du véhicule (facultatif).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='departure_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='departure_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Heure de départ habituelle.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='model',
            field=models.CharField(blank=True, help_text='Modèle du véhicule (facultatif).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='seats',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de places (important) si vous êtes conducteur.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('moto', 'Moto'), ('voiture', 'Voiture')], help_text='Type de véhicule si vous êtes conducteur.', max_length=10, null=True),
        ),
    ]
